networks:
  default:
    driver: bridge

services:
  trusted_playback:
    image: nexus.intern.cube-tec.com:8083/trusted-playback-grafana-dev:latest
    restart: unless-stopped
    container_name: gf
    volumes:       
      - trusted_playback:/var/lib/trusted_playback
      - grafana_data:/var/lib/grafana
    ports: 
      - "3000:3000"
    restart: always
    networks:
      - default

  prometheus:
    container_name: prom
    build: ./prometheus
    ports: 
      - "9090:9090"
    volumes: 
      - prometheus_data:/prometheus
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      #- prometheus_data:/etc/prometheus/prometheus.yml
    command: 
      - '--config.file=/etc/prometheus/prometheus.yml'
      #- '--config.file=/mount/x/Dev/Projects/Docker/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - "--web.console.libraries=/usr/share/prometheus/console_libraries" 
      - "--web.console.templates=/usr/share/prometheus/consoles"
    restart: always
    networks:
      - default

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: c-advisor
    ports:
    - 8080:8080
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
    depends_on:
    - redis
    networks:
      - default

  redis:
    image: redis:latest
    container_name: redis
    ports:
    - 6379:6379  
    networks:
      - default
  
  rust_api:
    build: ./rust_api
    container_name: rust_api
    ports:
      - 8300:8300
    networks:
      - default

  testing:
    build: ./testing
    container_name: testing
    ports:
      - 8000:8000
    networks:
      - default
  test:
    image: ubuntu
    container_name: test
    command: tail -f
      
    
volumes: 
  prometheus_data: {}
  grafana_data: {}
  trusted_playback: {}