[package]
name = "testing"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.11.0", features = ["full", "macros"] }
actix-web = "3.3.2"
actix-rt = "2.2.0"